In [3]:
import numpy as np
import scipy.io
import os
import cv2
import math
import matplotlib.pyplot as plt
import sklearn
import h5py
from scipy.io import loadmat
import data_preprocessing
# from data_preprocessing import extract_single_frame_from_displacementNorm
from data_preprocessing import process_one_patient

In [2]:
# data_dir = "/DATA/TBI/jesseDATA"
data_dir = "/DATA/TBI/phan92DATA/tbi_diagnosis/data/raw/cardiac_displacement_3_updated_Oct13"

In [3]:
mat = scipy.io.loadmat('/DATA/TBI/jesseDATA/DoD001/DoD001_Ter001_RC1_Displacement_Normalized_3.mat')

In [12]:
# mat.keys()
# # mat.values()

In [13]:
# x = mat.items()

In [14]:
# print(x)

In [15]:
# print(mat['displacementNorm'])

In [59]:
patient_1 = process_one_patient("/DATA/TBI/jesseDATA/DoD001", 256, 256, 1)

In [15]:
print(patient_1[0])
print(patient_1[1])
print(patient_1[2])
print(patient_1[3])

[[[[-3.32463601e-01]
   [-5.53795174e-01]
   [-7.84109660e-01]
   [-8.55661877e-01]
   [-1.43656344e+00]]

  [[-2.32570933e-02]
   [-7.08554721e-01]
   [-2.33333422e+00]
   [-4.92607010e-01]
   [ 1.58466670e+00]]

  [[ 3.02767022e-01]
   [ 4.45243929e-01]
   [ 4.45009817e-01]
   [ 8.08575081e-01]
   [-1.01220111e+00]]

  [[-1.25316001e-01]
   [ 1.47523323e-01]
   [ 1.94606966e+00]
   [ 1.53235786e+00]
   [ 1.91424146e+00]]

  [[-6.41224914e-01]
   [ 8.32184167e-02]
   [-5.42135654e-02]
   [ 2.06865216e-01]
   [-6.32360899e-02]]]


 [[[ 1.33402091e+00]
   [ 3.48027044e+00]
   [-4.48371638e-01]
   [ 5.66624213e-02]
   [ 2.13725897e-01]]

  [[ 1.34340725e+00]
   [ 9.75720267e-01]
   [-1.82651917e-01]
   [-2.93005594e-01]
   [-2.23052180e-01]]

  [[-9.02517627e-01]
   [ 2.44231414e-01]
   [ 9.74018894e-02]
   [-5.84132787e-01]
   [-9.84460490e-01]]

  [[-7.30012676e-01]
   [-5.54552447e-01]
   [-2.41543427e-01]
   [-5.69618311e-01]
   [ 9.26549196e-01]]

  [[-1.12701883e+00]
   [-8.5729619

In [9]:
type(patient_1)

tuple

In [60]:
len(patient_1)

4

In [23]:
type(patient_1[0])

numpy.ndarray

In [61]:
len(patient_1[0])

30

In [29]:
type(patient_1[0][0])

numpy.ndarray

In [62]:
len(patient_1[0][0])

256

In [34]:
print(patient_1[0][0])

[[[-0.3324636 ]
  [-0.55379517]
  [-0.78410966]
  [-0.85566188]
  [-1.43656344]]

 [[-0.02325709]
  [-0.70855472]
  [-2.33333422]
  [-0.49260701]
  [ 1.5846667 ]]

 [[ 0.30276702]
  [ 0.44524393]
  [ 0.44500982]
  [ 0.80857508]
  [-1.01220111]]

 [[-0.125316  ]
  [ 0.14752332]
  [ 1.94606966]
  [ 1.53235786]
  [ 1.91424146]]

 [[-0.64122491]
  [ 0.08321842]
  [-0.05421357]
  [ 0.20686522]
  [-0.06323609]]]


In [39]:
print(patient_1[0][0][0])

[[-0.3324636 ]
 [-0.55379517]
 [-0.78410966]
 [-0.85566188]
 [-1.43656344]]


In [65]:
frame_list = []

In [67]:
for i in range(0, 29):
    frame_list.append(np.average(patient_1[0][i]))

In [68]:
print(frame_list)

[3.469446951953614e-17, -5.551115123125783e-17, 8.326672684688674e-17, -6.938893903907228e-18, -1.734723475976807e-17, 1.1102230246251565e-16, 3.469446951953614e-17, 1.5612511283791264e-17, -3.469446951953614e-17, 6.938893903907228e-18, 3.209238430557093e-17, 2.7755575615628914e-17, 1.3877787807814457e-17, 2.6020852139652106e-17, -6.938893903907228e-18, 0.0, -4.163336342344337e-17, 1.3877787807814457e-17, 0.0, 1.3010426069826053e-17, 2.7755575615628914e-17, -1.3877787807814457e-17, -3.469446951953614e-17, 2.0816681711721685e-17, 2.7755575615628914e-17, -9.71445146547012e-17, -3.642919299551295e-17, -6.938893903907228e-18, -1.3877787807814457e-17]


In [70]:
max(frame_list)

1.1102230246251565e-16

In [71]:
frame_list.index(1.1102230246251565e-16)

5

In [72]:
np.argmax(frame_list)

5